services:
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka-broker
    hostname: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"    
      - "29092:29092"  
      - "9093:9093"    
    networks:
      - moti-network
    volumes:
      - kafka-data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 60s

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      kafka:
        condition: service_healthy
    restart: on-failure
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_CLUSTERS_0_READONLY: "false"
      LOGGING_LEVEL_ROOT: INFO
      LOGGING_LEVEL_COM_PROVECTUS: DEBUG
    ports:
      - "8080:8080"
    networks:
      - moti-network

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: motiuser
      POSTGRES_PASSWORD: motipass
      POSTGRES_DB: motidb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U motiuser -d motidb"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - moti-network

  user-service:
    build: ./user_service
    container_name: user-service
    command: gunicorn user_service.wsgi:application --bind 0.0.0.0:8000 --workers 1 --timeout 120
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: user_service.settings
      PORT: 8000
      PG_HOST: db
      PG_PORT: 5432
      PG_USER: motiuser
      PG_PASSWORD: motipass
      PG_DB: motidb
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_USER_EVENTS_TOPIC: user-events
    volumes:
      - ./user_service:/app
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - moti-network
    
  journey-service:
    build: ./journey_service
    container_name: journey-service
    command: gunicorn journey_service.wsgi:application --bind 0.0.0.0:8001 --workers 1 --timeout 120
    ports:
      - "8001:8001"
    environment:
      DJANGO_SETTINGS_MODULE: journey_service.settings
      PORT: 8001
      PG_HOST: db
      PG_USER: motiuser
      PG_PORT: 5432
      PG_PASSWORD: motipass
      PG_DB: journey_db
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_USER_EVENTS_TOPIC: user-events
      KAFKA_CONSUMER_GROUP_ID: journey-service-group 
    volumes:
      - ./journey_service:/app
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_healthy
      user-service:
        condition: service_started
    networks:
      - moti-network

networks:
  moti-network:
    driver: bridge
    name: moti-network

volumes:
  kafka-data:
  pgdata:
